services:
  jxwaf_base:
    image: "jxwaf/jxwaf:v4.2"
    ports:
      - "80:80"
      - "443:443"
    environment:
      HTTP_PORT: 80
      HTTPS_PORT: 443
      JXWAF_SERVER: you_jxwaf_server_url
      WAF_AUTH: you_auth_key 
      TZ: Asia/Shanghai
    restart: unless-stopped
    networks:
      - jxwaf_base_net

networks:
  jxwaf_base_net:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.20.0/24
