services:
  jxwaf_base_server:
    image: "jxwaf/jxwaf-mini-server:v4.3"
    ports:
      - "8000:8000"
    restart: unless-stopped
    networks:
      app_net:
        ipv4_address: 192.168.1.100

networks:
  app_net:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.1.0/24
