services:
  jxwaf_base_server:
    image: "jxwaf/jxwaf-mini-server:v4.3"
    ports:
      - "8000:8000"
    restart: unless-stopped
    networks:
      - jxwaf_base_server_net

networks:
  jxwaf_base_server_net:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.10.0/24
